export default {
  completed: 'Completed',
  abandonded: 'Abandoned',
  active: 'Active',
  launchedOn: 'Launched on',
  editedOn: 'Last edited on',
  endedOn: 'Ended on',
  studies: 'STUDIES',
  filter: 'FILTER',
  ongoing: 'ongoing',
  createStudy: 'Create a new study',
  basicInformation: 'Basic Information',
  title: 'Title',
  description: 'Description',
  of: 'of',
  cards: 'Cards',
  cardName: 'Card name',
  addCard: 'Add Card',
  message: 'Message',
  thanksMessage: 'Thanks message',
  inactive: 'Inactive',
  create: 'Create',
  participant: 'participant',
  cards: 'cards',
  categories: 'categories',
  similarityMatrix: 'similarity matrix',
  clusters: 'clusters',
};

