export default {
  abandonded: 'Abandoned',
  active: 'Active',
  addCard: 'Add Card',
  averageSort: 'average sort',
  basicInformation: 'Basic Information',
  card: 'card',
  cardName: 'Card name',
  cards: 'cards',
  cardsNo: 'cards no',
  cardsSorted: 'cards sorted',
  categories: 'categories',
  categoriesCreated: 'categories created',
  categoriesNo: 'categoriesNo',
  category: 'category',
  clusters: 'clusters',
  completed: 'Completed',
  completedTheStudy: 'completed the study',
  completion: 'completion',
  couldBeMergedInto: 'could be merged into',
  create: 'Create',
  createStudy: 'Create a new study',
  description: 'Description',
  editedOn: 'Last edited on',
  endedOn: 'Ended on',
  filter: 'FILTER',
  fillMeOut: 'fill me out',
  frequency: 'frequency',
  inactive: 'Inactive',
  launchedOn: 'Launched on',
  message: 'Message',
  noParticipantsYet: 'no participants yet',
  of: 'of',
  ofTheParticipants: 'of the participants.',
  ongoing: 'ongoing',
  outOf: 'out of',
  participant: 'participant',
  participantNo: 'participant no',
  participants: 'participants',
  similarity: 'similarity',
  similarityMatrix: 'similarity matrix',
  studies: 'STUDIES',
  studyCreated: 'Study created',
  thanksMessage: 'Thanks message',
  timeTaken: 'time taken',
  title: 'Title',
  users: 'users',
  wasGroupedTogetherBy: 'was grouped together by ',
  wereSorterInAverage: 'were sorter in average',
};

