export default {
  completed: 'Completed',
  abandonded: 'Abandoned',
  launchedOn: 'Launched on',
  editedOn: 'Last edited on',
  endedOn: 'Ended on',
  studies: 'STUDIES',
  filter: 'FILTER',
  ongoing: 'ongoing',
  createStudy: 'Create a new study',
  basicInformation: 'Basic Information',
  title: 'Title',
  description: 'Description',
  of: 'of',
  cards: 'Cards',
  cardName: 'Card name',
  addCard: 'Add Card',
  message: 'Message',
  thanksMessage: 'Thanks message',
};

