export default {
  addComment: 'add a comment',
  cancel: 'cancel',
  clickToRename: 'click here to rename',
  dropToAdd: 'drop to add',
  dropToCreateCategory: 'drop to create a category',
  studyNotFound: 'study not found',
  sumbit: 'sumbit',
  youCanCloseThisTab: 'you can close this tab',
  fillTitle: 'Fill all the titles',
  sameCategoryTitleNotAllowed: 'Same category title not allowed',
  confirmFinishUnSorted: 'You have unsorted cards, are you sure to finish? The sorting will not be continued.',
  confirmFinish: 'Are you sure to finish? The sorting will not be continued.',
  confirm: 'Confirm',
  cancel: 'Cancel',
  Demographic_Questions:'Demographic Questions',
};
