export default {
  addComment: 'add a comment',
  cancel: 'cancel',
  clickToRename: 'click here to rename',
  dropToAdd: 'drop to add',
  dropToCreateCategory: 'drop to create a category',
  studyNotFound: 'study not found',
  submit: 'Submit',
  youCanCloseThisTab: 'you can close this tab',
  fillTitle: 'Please fill in all the titles',
  sameCategoryTitleNotAllowed: 'Duplicate Category Titles Are Not Allowed. Duplicates: ',
  confirmFinishUnSorted: 'You have unsorted cards. Are you sure you want to finish? Sorting will not be continued.',
  confirmFinish: 'Are you sure you want to finish? Sorting will not be continued.',
  confirm: 'Confirm',
  cancel: 'Cancel',
  Questionnaire:'You can optionally complete the questionnaire by clicking on the following link:',
  noCategoryCreated: 'No categories created',
};
